### ISSUE TITLE
Not handling case where no HANA Instances found

### ISSUE THREAD

**Issue by andrewlunde** [SAP/cf-cli-smsi-plugin#1]
Throwing this error.

Using service manager = CAPMT_SMC
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
main.(*ServiceManagementPlugin).Run(0xc0000960c0, 0x13f8ea0, 0xc000092110, 0xc00011c1a0, 0x1, 0x1)
	/Users/i830671/git/cf-cli-smsi-plugin/ServiceManagement_plugin.go:308 +0x614d
code.cloudfoundry.org/cli/plugin.Start(0x13f2260, 0xc0000960c0)
	/Users/i830671/go/src/code.cloudfoundry.org/cli/plugin/plugin_shim.go:34 +0x1f2
main.main()
	/Users/i830671/git/cf-cli-smsi-plugin/ServiceManagement_plugin.go:870 +0x3d

**Comment by andrewlunde** [comment]
Fixed in release v1.2.0. -Andrew
